In [2]:
import numpy as np 

A = np.array([[56.0,0.0,4.4,68.0],
             [1.2,104.0,52.0,8.0],
             [1.8,135.0,99.0,0.9]])

A

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [3]:
cal = A.sum(axis = 0)
cal

array([ 59. , 239. , 155.4,  76.9])

In [6]:
# Manual reshaping
100 * A/cal.reshape(1,4)

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [5]:
# Auto broadcasting 
100 * A/cal

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [15]:
# broadcasting: 100 converted (1,4) vector
np.array([1, 2, 3, 4]) + 100 


array([101, 102, 103, 104])

In [16]:
# broadcasting: (m,n):(2,3) + (m,n) (1,3) -> (2,3) 
np.array([[1,2,3], [4,5,6]]) + [100, 200, 300]

array([[101, 202, 303],
       [104, 205, 306]])