In [1]:
import numpy as np 
a = np.random.randn(5)

In [2]:
print(a)

[-0.13748837  2.30348948 -0.63155176 -0.16877873 -2.45346424]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[-0.13748837  2.30348948 -0.63155176 -0.16877873 -2.45346424]


In [5]:
print(np.dot(a, a.T))

11.771797472458754


In [6]:
b = np.random.rand(5,1)
print(b)

[[0.716332  ]
 [0.14877575]
 [0.68208782]
 [0.16600566]
 [0.11375354]]


In [7]:
print(a.T)

[-0.13748837  2.30348948 -0.63155176 -0.16877873 -2.45346424]


In [10]:
a = np.random.randn(1,3)
b = np.random.randn(3,3)
c = a * b
c.shape

(3, 3)

In [11]:
a = np.array([[2,1],[1,3]])

In [12]:
a * a 

array([[4, 1],
       [1, 9]])

In [13]:
a = np.random.randn(3,4)
a

array([[ 0.22235081,  0.8500676 , -0.2056215 ,  0.03272371],
       [-1.99551607, -0.89869364, -0.16601378, -2.24945528],
       [-1.06110554,  0.43167344, -1.47763735, -1.19892714]])

In [14]:
b = np.random.randn(4,1)
b 

array([[0.64909614],
       [0.68230561],
       [0.64553731],
       [0.77232141]])

In [17]:
a.T

array([[ 0.22235081, -1.99551607, -1.06110554],
       [ 0.8500676 , -0.89869364,  0.43167344],
       [-0.2056215 , -0.16601378, -1.47763735],
       [ 0.03272371, -2.24945528, -1.19892714]])

In [18]:
a.T + b

array([[ 0.87144695, -1.34641993, -0.41200939],
       [ 1.53237321, -0.21638803,  1.11397905],
       [ 0.43991581,  0.47952353, -0.83210004],
       [ 0.80504512, -1.47713387, -0.42660573]])